// Code generated by ogen, DO NOT EDIT.

package queue

import (
	"time"

	"github.com/go-faster/errors"
)

type ApiKeyAuth struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *ApiKeyAuth) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *ApiKeyAuth) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *ApiKeyAuth) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *ApiKeyAuth) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *ApiKeyAuth) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *ApiKeyAuth) SetRoles(val []string) {
	s.Roles = val
}

type ClearQueueBadRequest Error

func (*ClearQueueBadRequest) clearQueueRes() {}

type ClearQueueInternalServerError Error

func (*ClearQueueInternalServerError) clearQueueRes() {}

type ClearQueueNotFound Error

func (*ClearQueueNotFound) clearQueueRes() {}

type ClearQueueOK struct {
	SimpleMQ OptClearQueueOKSimpleMQ `json:"SimpleMQ"`
	IsOk     OptBool                 `json:"is_ok"`
}

// GetSimpleMQ returns the value of SimpleMQ.
func (s *ClearQueueOK) GetSimpleMQ() OptClearQueueOKSimpleMQ {
	return s.SimpleMQ
}

// GetIsOk returns the value of IsOk.
func (s *ClearQueueOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetSimpleMQ sets the value of SimpleMQ.
func (s *ClearQueueOK) SetSimpleMQ(val OptClearQueueOKSimpleMQ) {
	s.SimpleMQ = val
}

// SetIsOk sets the value of IsOk.
func (s *ClearQueueOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*ClearQueueOK) clearQueueRes() {}

type ClearQueueOKSimpleMQ struct {
	Result OptString `json:"result"`
}

// GetResult returns the value of Result.
func (s *ClearQueueOKSimpleMQ) GetResult() OptString {
	return s.Result
}

// SetResult sets the value of Result.
func (s *ClearQueueOKSimpleMQ) SetResult(val OptString) {
	s.Result = val
}

type ClearQueueUnauthorized Error

func (*ClearQueueUnauthorized) clearQueueRes() {}

// Ref: #/components/schemas/CommonServiceItem
type CommonServiceItem struct {
	ID CommonServiceItemID `json:"ID"`
	// リソース名.
	Name         string                      `json:"Name"`
	Description  OptNilString                `json:"Description"`
	Settings     Settings                    `json:"Settings"`
	SettingsHash string                      `json:"SettingsHash"`
	Status       Status                      `json:"Status"`
	ServiceClass string                      `json:"ServiceClass"`
	Availability string                      `json:"Availability"`
	CreatedAt    time.Time                   `json:"CreatedAt"`
	ModifiedAt   time.Time                   `json:"ModifiedAt"`
	Provider     Provider                    `json:"Provider"`
	Icon         OptNilCommonServiceItemIcon `json:"Icon"`
	Tags         []string                    `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CommonServiceItem) GetID() CommonServiceItemID {
	return s.ID
}

// GetName returns the value of Name.
func (s *CommonServiceItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CommonServiceItem) GetDescription() OptNilString {
	return s.Description
}

// GetSettings returns the value of Settings.
func (s *CommonServiceItem) GetSettings() Settings {
	return s.Settings
}

// GetSettingsHash returns the value of SettingsHash.
func (s *CommonServiceItem) GetSettingsHash() string {
	return s.SettingsHash
}

// GetStatus returns the value of Status.
func (s *CommonServiceItem) GetStatus() Status {
	return s.Status
}

// GetServiceClass returns the value of ServiceClass.
func (s *CommonServiceItem) GetServiceClass() string {
	return s.ServiceClass
}

// GetAvailability returns the value of Availability.
func (s *CommonServiceItem) GetAvailability() string {
	return s.Availability
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CommonServiceItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CommonServiceItem) GetModifiedAt() time.Time {
	return s.ModifiedAt
}

// GetProvider returns the value of Provider.
func (s *CommonServiceItem) GetProvider() Provider {
	return s.Provider
}

// GetIcon returns the value of Icon.
func (s *CommonServiceItem) GetIcon() OptNilCommonServiceItemIcon {
	return s.Icon
}

// GetTags returns the value of Tags.
func (s *CommonServiceItem) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CommonServiceItem) SetID(val CommonServiceItemID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CommonServiceItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CommonServiceItem) SetDescription(val OptNilString) {
	s.Description = val
}

// SetSettings sets the value of Settings.
func (s *CommonServiceItem) SetSettings(val Settings) {
	s.Settings = val
}

// SetSettingsHash sets the value of SettingsHash.
func (s *CommonServiceItem) SetSettingsHash(val string) {
	s.SettingsHash = val
}

// SetStatus sets the value of Status.
func (s *CommonServiceItem) SetStatus(val Status) {
	s.Status = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CommonServiceItem) SetServiceClass(val string) {
	s.ServiceClass = val
}

// SetAvailability sets the value of Availability.
func (s *CommonServiceItem) SetAvailability(val string) {
	s.Availability = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CommonServiceItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CommonServiceItem) SetModifiedAt(val time.Time) {
	s.ModifiedAt = val
}

// SetProvider sets the value of Provider.
func (s *CommonServiceItem) SetProvider(val Provider) {
	s.Provider = val
}

// SetIcon sets the value of Icon.
func (s *CommonServiceItem) SetIcon(val OptNilCommonServiceItemIcon) {
	s.Icon = val
}

// SetTags sets the value of Tags.
func (s *CommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// CommonServiceItemID represents sum type.
type CommonServiceItemID struct {
	Type   CommonServiceItemIDType // switch on this field
	String string
	Int    int
}

// CommonServiceItemIDType is oneOf type of CommonServiceItemID.
type CommonServiceItemIDType string

// Possible values for CommonServiceItemIDType.
const (
	StringCommonServiceItemID CommonServiceItemIDType = "string"
	IntCommonServiceItemID    CommonServiceItemIDType = "int"
)

// IsString reports whether CommonServiceItemID is string.
func (s CommonServiceItemID) IsString() bool { return s.Type == StringCommonServiceItemID }

// IsInt reports whether CommonServiceItemID is int.
func (s CommonServiceItemID) IsInt() bool { return s.Type == IntCommonServiceItemID }

// SetString sets CommonServiceItemID to string.
func (s *CommonServiceItemID) SetString(v string) {
	s.Type = StringCommonServiceItemID
	s.String = v
}

// GetString returns string and true boolean if CommonServiceItemID is string.
func (s CommonServiceItemID) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCommonServiceItemID returns new CommonServiceItemID from string.
func NewStringCommonServiceItemID(v string) CommonServiceItemID {
	var s CommonServiceItemID
	s.SetString(v)
	return s
}

// SetInt sets CommonServiceItemID to int.
func (s *CommonServiceItemID) SetInt(v int) {
	s.Type = IntCommonServiceItemID
	s.Int = v
}

// GetInt returns int and true boolean if CommonServiceItemID is int.
func (s CommonServiceItemID) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntCommonServiceItemID returns new CommonServiceItemID from int.
func NewIntCommonServiceItemID(v int) CommonServiceItemID {
	var s CommonServiceItemID
	s.SetInt(v)
	return s
}

type CommonServiceItemIcon struct {
	// 0を指定することでIconなしに設定することが出来ます.
	ID    OptCommonServiceItemIconID `json:"ID"`
	URL   OptString                  `json:"URL"`
	Name  OptString                  `json:"Name"`
	Scope OptString                  `json:"Scope"`
	Tags  []string                   `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CommonServiceItemIcon) GetID() OptCommonServiceItemIconID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *CommonServiceItemIcon) GetURL() OptString {
	return s.URL
}

// GetName returns the value of Name.
func (s *CommonServiceItemIcon) GetName() OptString {
	return s.Name
}

// GetScope returns the value of Scope.
func (s *CommonServiceItemIcon) GetScope() OptString {
	return s.Scope
}

// GetTags returns the value of Tags.
func (s *CommonServiceItemIcon) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CommonServiceItemIcon) SetID(val OptCommonServiceItemIconID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *CommonServiceItemIcon) SetURL(val OptString) {
	s.URL = val
}

// SetName sets the value of Name.
func (s *CommonServiceItemIcon) SetName(val OptString) {
	s.Name = val
}

// SetScope sets the value of Scope.
func (s *CommonServiceItemIcon) SetScope(val OptString) {
	s.Scope = val
}

// SetTags sets the value of Tags.
func (s *CommonServiceItemIcon) SetTags(val []string) {
	s.Tags = val
}

// 0を指定することでIconなしに設定することが出来ます.
// CommonServiceItemIconID represents sum type.
type CommonServiceItemIconID struct {
	Type   CommonServiceItemIconIDType // switch on this field
	String string
	Int    int
}

// CommonServiceItemIconIDType is oneOf type of CommonServiceItemIconID.
type CommonServiceItemIconIDType string

// Possible values for CommonServiceItemIconIDType.
const (
	StringCommonServiceItemIconID CommonServiceItemIconIDType = "string"
	IntCommonServiceItemIconID    CommonServiceItemIconIDType = "int"
)

// IsString reports whether CommonServiceItemIconID is string.
func (s CommonServiceItemIconID) IsString() bool { return s.Type == StringCommonServiceItemIconID }

// IsInt reports whether CommonServiceItemIconID is int.
func (s CommonServiceItemIconID) IsInt() bool { return s.Type == IntCommonServiceItemIconID }

// SetString sets CommonServiceItemIconID to string.
func (s *CommonServiceItemIconID) SetString(v string) {
	s.Type = StringCommonServiceItemIconID
	s.String = v
}

// GetString returns string and true boolean if CommonServiceItemIconID is string.
func (s CommonServiceItemIconID) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCommonServiceItemIconID returns new CommonServiceItemIconID from string.
func NewStringCommonServiceItemIconID(v string) CommonServiceItemIconID {
	var s CommonServiceItemIconID
	s.SetString(v)
	return s
}

// SetInt sets CommonServiceItemIconID to int.
func (s *CommonServiceItemIconID) SetInt(v int) {
	s.Type = IntCommonServiceItemIconID
	s.Int = v
}

// GetInt returns int and true boolean if CommonServiceItemIconID is int.
func (s CommonServiceItemIconID) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntCommonServiceItemIconID returns new CommonServiceItemIconID from int.
func NewIntCommonServiceItemIconID(v int) CommonServiceItemIconID {
	var s CommonServiceItemIconID
	s.SetInt(v)
	return s
}

type ConfigQueueBadRequest Error

func (*ConfigQueueBadRequest) configQueueRes() {}

type ConfigQueueInternalServerError Error

func (*ConfigQueueInternalServerError) configQueueRes() {}

type ConfigQueueNotFound Error

func (*ConfigQueueNotFound) configQueueRes() {}

type ConfigQueueOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
	Success           OptBool           `json:"Success"`
	IsOk              OptBool           `json:"is_ok"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *ConfigQueueOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// GetSuccess returns the value of Success.
func (s *ConfigQueueOK) GetSuccess() OptBool {
	return s.Success
}

// GetIsOk returns the value of IsOk.
func (s *ConfigQueueOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *ConfigQueueOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// SetSuccess sets the value of Success.
func (s *ConfigQueueOK) SetSuccess(val OptBool) {
	s.Success = val
}

// SetIsOk sets the value of IsOk.
func (s *ConfigQueueOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*ConfigQueueOK) configQueueRes() {}

// Ref: #/components/schemas/ConfigQueueRequest
type ConfigQueueRequest struct {
	CommonServiceItem ConfigQueueRequestCommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *ConfigQueueRequest) GetCommonServiceItem() ConfigQueueRequestCommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *ConfigQueueRequest) SetCommonServiceItem(val ConfigQueueRequestCommonServiceItem) {
	s.CommonServiceItem = val
}

type ConfigQueueRequestCommonServiceItem struct {
	Description OptString                                     `json:"Description"`
	Settings    Settings                                      `json:"Settings"`
	Tags        []string                                      `json:"Tags"`
	Icon        OptNilConfigQueueRequestCommonServiceItemIcon `json:"Icon"`
}

// GetDescription returns the value of Description.
func (s *ConfigQueueRequestCommonServiceItem) GetDescription() OptString {
	return s.Description
}

// GetSettings returns the value of Settings.
func (s *ConfigQueueRequestCommonServiceItem) GetSettings() Settings {
	return s.Settings
}

// GetTags returns the value of Tags.
func (s *ConfigQueueRequestCommonServiceItem) GetTags() []string {
	return s.Tags
}

// GetIcon returns the value of Icon.
func (s *ConfigQueueRequestCommonServiceItem) GetIcon() OptNilConfigQueueRequestCommonServiceItemIcon {
	return s.Icon
}

// SetDescription sets the value of Description.
func (s *ConfigQueueRequestCommonServiceItem) SetDescription(val OptString) {
	s.Description = val
}

// SetSettings sets the value of Settings.
func (s *ConfigQueueRequestCommonServiceItem) SetSettings(val Settings) {
	s.Settings = val
}

// SetTags sets the value of Tags.
func (s *ConfigQueueRequestCommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// SetIcon sets the value of Icon.
func (s *ConfigQueueRequestCommonServiceItem) SetIcon(val OptNilConfigQueueRequestCommonServiceItemIcon) {
	s.Icon = val
}

type ConfigQueueRequestCommonServiceItemIcon struct {
	// 0を指定することでIconなしに設定することが出来ます.
	ID    OptConfigQueueRequestCommonServiceItemIconID `json:"ID"`
	URL   OptString                                    `json:"URL"`
	Name  OptString                                    `json:"Name"`
	Scope OptString                                    `json:"Scope"`
	Tags  []string                                     `json:"Tags"`
}

// GetID returns the value of ID.
func (s *ConfigQueueRequestCommonServiceItemIcon) GetID() OptConfigQueueRequestCommonServiceItemIconID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *ConfigQueueRequestCommonServiceItemIcon) GetURL() OptString {
	return s.URL
}

// GetName returns the value of Name.
func (s *ConfigQueueRequestCommonServiceItemIcon) GetName() OptString {
	return s.Name
}

// GetScope returns the value of Scope.
func (s *ConfigQueueRequestCommonServiceItemIcon) GetScope() OptString {
	return s.Scope
}

// GetTags returns the value of Tags.
func (s *ConfigQueueRequestCommonServiceItemIcon) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *ConfigQueueRequestCommonServiceItemIcon) SetID(val OptConfigQueueRequestCommonServiceItemIconID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *ConfigQueueRequestCommonServiceItemIcon) SetURL(val OptString) {
	s.URL = val
}

// SetName sets the value of Name.
func (s *ConfigQueueRequestCommonServiceItemIcon) SetName(val OptString) {
	s.Name = val
}

// SetScope sets the value of Scope.
func (s *ConfigQueueRequestCommonServiceItemIcon) SetScope(val OptString) {
	s.Scope = val
}

// SetTags sets the value of Tags.
func (s *ConfigQueueRequestCommonServiceItemIcon) SetTags(val []string) {
	s.Tags = val
}

// 0を指定することでIconなしに設定することが出来ます.
// ConfigQueueRequestCommonServiceItemIconID represents sum type.
type ConfigQueueRequestCommonServiceItemIconID struct {
	Type   ConfigQueueRequestCommonServiceItemIconIDType // switch on this field
	String string
	Int    int
}

// ConfigQueueRequestCommonServiceItemIconIDType is oneOf type of ConfigQueueRequestCommonServiceItemIconID.
type ConfigQueueRequestCommonServiceItemIconIDType string

// Possible values for ConfigQueueRequestCommonServiceItemIconIDType.
const (
	StringConfigQueueRequestCommonServiceItemIconID ConfigQueueRequestCommonServiceItemIconIDType = "string"
	IntConfigQueueRequestCommonServiceItemIconID    ConfigQueueRequestCommonServiceItemIconIDType = "int"
)

// IsString reports whether ConfigQueueRequestCommonServiceItemIconID is string.
func (s ConfigQueueRequestCommonServiceItemIconID) IsString() bool {
	return s.Type == StringConfigQueueRequestCommonServiceItemIconID
}

// IsInt reports whether ConfigQueueRequestCommonServiceItemIconID is int.
func (s ConfigQueueRequestCommonServiceItemIconID) IsInt() bool {
	return s.Type == IntConfigQueueRequestCommonServiceItemIconID
}

// SetString sets ConfigQueueRequestCommonServiceItemIconID to string.
func (s *ConfigQueueRequestCommonServiceItemIconID) SetString(v string) {
	s.Type = StringConfigQueueRequestCommonServiceItemIconID
	s.String = v
}

// GetString returns string and true boolean if ConfigQueueRequestCommonServiceItemIconID is string.
func (s ConfigQueueRequestCommonServiceItemIconID) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringConfigQueueRequestCommonServiceItemIconID returns new ConfigQueueRequestCommonServiceItemIconID from string.
func NewStringConfigQueueRequestCommonServiceItemIconID(v string) ConfigQueueRequestCommonServiceItemIconID {
	var s ConfigQueueRequestCommonServiceItemIconID
	s.SetString(v)
	return s
}

// SetInt sets ConfigQueueRequestCommonServiceItemIconID to int.
func (s *ConfigQueueRequestCommonServiceItemIconID) SetInt(v int) {
	s.Type = IntConfigQueueRequestCommonServiceItemIconID
	s.Int = v
}

// GetInt returns int and true boolean if ConfigQueueRequestCommonServiceItemIconID is int.
func (s ConfigQueueRequestCommonServiceItemIconID) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntConfigQueueRequestCommonServiceItemIconID returns new ConfigQueueRequestCommonServiceItemIconID from int.
func NewIntConfigQueueRequestCommonServiceItemIconID(v int) ConfigQueueRequestCommonServiceItemIconID {
	var s ConfigQueueRequestCommonServiceItemIconID
	s.SetInt(v)
	return s
}

type ConfigQueueUnauthorized Error

func (*ConfigQueueUnauthorized) configQueueRes() {}

type CreateQueueBadRequest Error

func (*CreateQueueBadRequest) createQueueRes() {}

type CreateQueueConflict Error

func (*CreateQueueConflict) createQueueRes() {}

type CreateQueueCreated struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
	Success           OptBool           `json:"Success"`
	IsOk              OptBool           `json:"is_ok"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *CreateQueueCreated) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// GetSuccess returns the value of Success.
func (s *CreateQueueCreated) GetSuccess() OptBool {
	return s.Success
}

// GetIsOk returns the value of IsOk.
func (s *CreateQueueCreated) GetIsOk() OptBool {
	return s.IsOk
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *CreateQueueCreated) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// SetSuccess sets the value of Success.
func (s *CreateQueueCreated) SetSuccess(val OptBool) {
	s.Success = val
}

// SetIsOk sets the value of IsOk.
func (s *CreateQueueCreated) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*CreateQueueCreated) createQueueRes() {}

type CreateQueueInternalServerError Error

func (*CreateQueueInternalServerError) createQueueRes() {}

// Ref: #/components/schemas/CreateQueueRequest
type CreateQueueRequest struct {
	CommonServiceItem CreateQueueRequestCommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *CreateQueueRequest) GetCommonServiceItem() CreateQueueRequestCommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *CreateQueueRequest) SetCommonServiceItem(val CreateQueueRequestCommonServiceItem) {
	s.CommonServiceItem = val
}

type CreateQueueRequestCommonServiceItem struct {
	Name        QueueName                                     `json:"Name"`
	Description OptString                                     `json:"Description"`
	Provider    CreateQueueRequestCommonServiceItemProvider   `json:"Provider"`
	Tags        []string                                      `json:"Tags"`
	Icon        OptNilCreateQueueRequestCommonServiceItemIcon `json:"Icon"`
}

// GetName returns the value of Name.
func (s *CreateQueueRequestCommonServiceItem) GetName() QueueName {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateQueueRequestCommonServiceItem) GetDescription() OptString {
	return s.Description
}

// GetProvider returns the value of Provider.
func (s *CreateQueueRequestCommonServiceItem) GetProvider() CreateQueueRequestCommonServiceItemProvider {
	return s.Provider
}

// GetTags returns the value of Tags.
func (s *CreateQueueRequestCommonServiceItem) GetTags() []string {
	return s.Tags
}

// GetIcon returns the value of Icon.
func (s *CreateQueueRequestCommonServiceItem) GetIcon() OptNilCreateQueueRequestCommonServiceItemIcon {
	return s.Icon
}

// SetName sets the value of Name.
func (s *CreateQueueRequestCommonServiceItem) SetName(val QueueName) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateQueueRequestCommonServiceItem) SetDescription(val OptString) {
	s.Description = val
}

// SetProvider sets the value of Provider.
func (s *CreateQueueRequestCommonServiceItem) SetProvider(val CreateQueueRequestCommonServiceItemProvider) {
	s.Provider = val
}

// SetTags sets the value of Tags.
func (s *CreateQueueRequestCommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// SetIcon sets the value of Icon.
func (s *CreateQueueRequestCommonServiceItem) SetIcon(val OptNilCreateQueueRequestCommonServiceItemIcon) {
	s.Icon = val
}

type CreateQueueRequestCommonServiceItemIcon struct {
	// 0を指定することでIconなしに設定することが出来ます.
	ID    OptCreateQueueRequestCommonServiceItemIconID `json:"ID"`
	URL   OptString                                    `json:"URL"`
	Name  OptString                                    `json:"Name"`
	Scope OptString                                    `json:"Scope"`
	Tags  []string                                     `json:"Tags"`
}

// GetID returns the value of ID.
func (s *CreateQueueRequestCommonServiceItemIcon) GetID() OptCreateQueueRequestCommonServiceItemIconID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *CreateQueueRequestCommonServiceItemIcon) GetURL() OptString {
	return s.URL
}

// GetName returns the value of Name.
func (s *CreateQueueRequestCommonServiceItemIcon) GetName() OptString {
	return s.Name
}

// GetScope returns the value of Scope.
func (s *CreateQueueRequestCommonServiceItemIcon) GetScope() OptString {
	return s.Scope
}

// GetTags returns the value of Tags.
func (s *CreateQueueRequestCommonServiceItemIcon) GetTags() []string {
	return s.Tags
}

// SetID sets the value of ID.
func (s *CreateQueueRequestCommonServiceItemIcon) SetID(val OptCreateQueueRequestCommonServiceItemIconID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *CreateQueueRequestCommonServiceItemIcon) SetURL(val OptString) {
	s.URL = val
}

// SetName sets the value of Name.
func (s *CreateQueueRequestCommonServiceItemIcon) SetName(val OptString) {
	s.Name = val
}

// SetScope sets the value of Scope.
func (s *CreateQueueRequestCommonServiceItemIcon) SetScope(val OptString) {
	s.Scope = val
}

// SetTags sets the value of Tags.
func (s *CreateQueueRequestCommonServiceItemIcon) SetTags(val []string) {
	s.Tags = val
}

// 0を指定することでIconなしに設定することが出来ます.
// CreateQueueRequestCommonServiceItemIconID represents sum type.
type CreateQueueRequestCommonServiceItemIconID struct {
	Type   CreateQueueRequestCommonServiceItemIconIDType // switch on this field
	String string
	Int    int
}

// CreateQueueRequestCommonServiceItemIconIDType is oneOf type of CreateQueueRequestCommonServiceItemIconID.
type CreateQueueRequestCommonServiceItemIconIDType string

// Possible values for CreateQueueRequestCommonServiceItemIconIDType.
const (
	StringCreateQueueRequestCommonServiceItemIconID CreateQueueRequestCommonServiceItemIconIDType = "string"
	IntCreateQueueRequestCommonServiceItemIconID    CreateQueueRequestCommonServiceItemIconIDType = "int"
)

// IsString reports whether CreateQueueRequestCommonServiceItemIconID is string.
func (s CreateQueueRequestCommonServiceItemIconID) IsString() bool {
	return s.Type == StringCreateQueueRequestCommonServiceItemIconID
}

// IsInt reports whether CreateQueueRequestCommonServiceItemIconID is int.
func (s CreateQueueRequestCommonServiceItemIconID) IsInt() bool {
	return s.Type == IntCreateQueueRequestCommonServiceItemIconID
}

// SetString sets CreateQueueRequestCommonServiceItemIconID to string.
func (s *CreateQueueRequestCommonServiceItemIconID) SetString(v string) {
	s.Type = StringCreateQueueRequestCommonServiceItemIconID
	s.String = v
}

// GetString returns string and true boolean if CreateQueueRequestCommonServiceItemIconID is string.
func (s CreateQueueRequestCommonServiceItemIconID) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCreateQueueRequestCommonServiceItemIconID returns new CreateQueueRequestCommonServiceItemIconID from string.
func NewStringCreateQueueRequestCommonServiceItemIconID(v string) CreateQueueRequestCommonServiceItemIconID {
	var s CreateQueueRequestCommonServiceItemIconID
	s.SetString(v)
	return s
}

// SetInt sets CreateQueueRequestCommonServiceItemIconID to int.
func (s *CreateQueueRequestCommonServiceItemIconID) SetInt(v int) {
	s.Type = IntCreateQueueRequestCommonServiceItemIconID
	s.Int = v
}

// GetInt returns int and true boolean if CreateQueueRequestCommonServiceItemIconID is int.
func (s CreateQueueRequestCommonServiceItemIconID) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntCreateQueueRequestCommonServiceItemIconID returns new CreateQueueRequestCommonServiceItemIconID from int.
func NewIntCreateQueueRequestCommonServiceItemIconID(v int) CreateQueueRequestCommonServiceItemIconID {
	var s CreateQueueRequestCommonServiceItemIconID
	s.SetInt(v)
	return s
}

type CreateQueueRequestCommonServiceItemProvider struct {
	Class CreateQueueRequestCommonServiceItemProviderClass `json:"Class"`
}

// GetClass returns the value of Class.
func (s *CreateQueueRequestCommonServiceItemProvider) GetClass() CreateQueueRequestCommonServiceItemProviderClass {
	return s.Class
}

// SetClass sets the value of Class.
func (s *CreateQueueRequestCommonServiceItemProvider) SetClass(val CreateQueueRequestCommonServiceItemProviderClass) {
	s.Class = val
}

type CreateQueueRequestCommonServiceItemProviderClass string

const (
	CreateQueueRequestCommonServiceItemProviderClassSimplemq CreateQueueRequestCommonServiceItemProviderClass = "simplemq"
)

// AllValues returns all CreateQueueRequestCommonServiceItemProviderClass values.
func (CreateQueueRequestCommonServiceItemProviderClass) AllValues() []CreateQueueRequestCommonServiceItemProviderClass {
	return []CreateQueueRequestCommonServiceItemProviderClass{
		CreateQueueRequestCommonServiceItemProviderClassSimplemq,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateQueueRequestCommonServiceItemProviderClass) MarshalText() ([]byte, error) {
	switch s {
	case CreateQueueRequestCommonServiceItemProviderClassSimplemq:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateQueueRequestCommonServiceItemProviderClass) UnmarshalText(data []byte) error {
	switch CreateQueueRequestCommonServiceItemProviderClass(data) {
	case CreateQueueRequestCommonServiceItemProviderClassSimplemq:
		*s = CreateQueueRequestCommonServiceItemProviderClassSimplemq
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateQueueUnauthorized Error

func (*CreateQueueUnauthorized) createQueueRes() {}

type DeleteQueueBadRequest Error

func (*DeleteQueueBadRequest) deleteQueueRes() {}

type DeleteQueueInternalServerError Error

func (*DeleteQueueInternalServerError) deleteQueueRes() {}

type DeleteQueueNotFound Error

func (*DeleteQueueNotFound) deleteQueueRes() {}

type DeleteQueueOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
	Success           OptBool           `json:"Success"`
	IsOk              OptBool           `json:"is_ok"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *DeleteQueueOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// GetSuccess returns the value of Success.
func (s *DeleteQueueOK) GetSuccess() OptBool {
	return s.Success
}

// GetIsOk returns the value of IsOk.
func (s *DeleteQueueOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *DeleteQueueOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// SetSuccess sets the value of Success.
func (s *DeleteQueueOK) SetSuccess(val OptBool) {
	s.Success = val
}

// SetIsOk sets the value of IsOk.
func (s *DeleteQueueOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*DeleteQueueOK) deleteQueueRes() {}

type DeleteQueueUnauthorized Error

func (*DeleteQueueUnauthorized) deleteQueueRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	IsFatal   OptBool   `json:"is_fatal"`
	Serial    OptString `json:"serial"`
	Status    OptString `json:"status"`
	ErrorCode OptString `json:"error_code"`
	ErrorMsg  OptString `json:"error_msg"`
}

// GetIsFatal returns the value of IsFatal.
func (s *Error) GetIsFatal() OptBool {
	return s.IsFatal
}

// GetSerial returns the value of Serial.
func (s *Error) GetSerial() OptString {
	return s.Serial
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() OptString {
	return s.Status
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() OptString {
	return s.ErrorCode
}

// GetErrorMsg returns the value of ErrorMsg.
func (s *Error) GetErrorMsg() OptString {
	return s.ErrorMsg
}

// SetIsFatal sets the value of IsFatal.
func (s *Error) SetIsFatal(val OptBool) {
	s.IsFatal = val
}

// SetSerial sets the value of Serial.
func (s *Error) SetSerial(val OptString) {
	s.Serial = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val OptString) {
	s.Status = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val OptString) {
	s.ErrorCode = val
}

// SetErrorMsg sets the value of ErrorMsg.
func (s *Error) SetErrorMsg(val OptString) {
	s.ErrorMsg = val
}

type ExpireSeconds int

type GetMessageCountBadRequest Error

func (*GetMessageCountBadRequest) getMessageCountRes() {}

type GetMessageCountInternalServerError Error

func (*GetMessageCountInternalServerError) getMessageCountRes() {}

type GetMessageCountNotFound Error

func (*GetMessageCountNotFound) getMessageCountRes() {}

type GetMessageCountOK struct {
	SimpleMQ GetMessageCountOKSimpleMQ `json:"SimpleMQ"`
	IsOk     OptBool                   `json:"is_ok"`
}

// GetSimpleMQ returns the value of SimpleMQ.
func (s *GetMessageCountOK) GetSimpleMQ() GetMessageCountOKSimpleMQ {
	return s.SimpleMQ
}

// GetIsOk returns the value of IsOk.
func (s *GetMessageCountOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetSimpleMQ sets the value of SimpleMQ.
func (s *GetMessageCountOK) SetSimpleMQ(val GetMessageCountOKSimpleMQ) {
	s.SimpleMQ = val
}

// SetIsOk sets the value of IsOk.
func (s *GetMessageCountOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*GetMessageCountOK) getMessageCountRes() {}

type GetMessageCountOKSimpleMQ struct {
	Result OptString `json:"result"`
	Count  int       `json:"count"`
}

// GetResult returns the value of Result.
func (s *GetMessageCountOKSimpleMQ) GetResult() OptString {
	return s.Result
}

// GetCount returns the value of Count.
func (s *GetMessageCountOKSimpleMQ) GetCount() int {
	return s.Count
}

// SetResult sets the value of Result.
func (s *GetMessageCountOKSimpleMQ) SetResult(val OptString) {
	s.Result = val
}

// SetCount sets the value of Count.
func (s *GetMessageCountOKSimpleMQ) SetCount(val int) {
	s.Count = val
}

type GetMessageCountUnauthorized Error

func (*GetMessageCountUnauthorized) getMessageCountRes() {}

type GetQueueBadRequest Error

func (*GetQueueBadRequest) getQueueRes() {}

type GetQueueInternalServerError Error

func (*GetQueueInternalServerError) getQueueRes() {}

type GetQueueNotFound Error

func (*GetQueueNotFound) getQueueRes() {}

type GetQueueOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
	IsOk              OptBool           `json:"is_ok"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *GetQueueOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// GetIsOk returns the value of IsOk.
func (s *GetQueueOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *GetQueueOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// SetIsOk sets the value of IsOk.
func (s *GetQueueOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*GetQueueOK) getQueueRes() {}

type GetQueueUnauthorized Error

func (*GetQueueUnauthorized) getQueueRes() {}

type GetQueuesBadRequest Error

func (*GetQueuesBadRequest) getQueuesRes() {}

type GetQueuesInternalServerError Error

func (*GetQueuesInternalServerError) getQueuesRes() {}

type GetQueuesOK struct {
	From               OptInt              `json:"From"`
	Count              OptInt              `json:"Count"`
	Total              OptInt              `json:"Total"`
	CommonServiceItems []CommonServiceItem `json:"CommonServiceItems"`
	IsOk               OptBool             `json:"is_ok"`
}

// GetFrom returns the value of From.
func (s *GetQueuesOK) GetFrom() OptInt {
	return s.From
}

// GetCount returns the value of Count.
func (s *GetQueuesOK) GetCount() OptInt {
	return s.Count
}

// GetTotal returns the value of Total.
func (s *GetQueuesOK) GetTotal() OptInt {
	return s.Total
}

// GetCommonServiceItems returns the value of CommonServiceItems.
func (s *GetQueuesOK) GetCommonServiceItems() []CommonServiceItem {
	return s.CommonServiceItems
}

// GetIsOk returns the value of IsOk.
func (s *GetQueuesOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetFrom sets the value of From.
func (s *GetQueuesOK) SetFrom(val OptInt) {
	s.From = val
}

// SetCount sets the value of Count.
func (s *GetQueuesOK) SetCount(val OptInt) {
	s.Count = val
}

// SetTotal sets the value of Total.
func (s *GetQueuesOK) SetTotal(val OptInt) {
	s.Total = val
}

// SetCommonServiceItems sets the value of CommonServiceItems.
func (s *GetQueuesOK) SetCommonServiceItems(val []CommonServiceItem) {
	s.CommonServiceItems = val
}

// SetIsOk sets the value of IsOk.
func (s *GetQueuesOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*GetQueuesOK) getQueuesRes() {}

type GetQueuesUnauthorized Error

func (*GetQueuesUnauthorized) getQueuesRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptClearQueueOKSimpleMQ returns new OptClearQueueOKSimpleMQ with value set to v.
func NewOptClearQueueOKSimpleMQ(v ClearQueueOKSimpleMQ) OptClearQueueOKSimpleMQ {
	return OptClearQueueOKSimpleMQ{
		Value: v,
		Set:   true,
	}
}

// OptClearQueueOKSimpleMQ is optional ClearQueueOKSimpleMQ.
type OptClearQueueOKSimpleMQ struct {
	Value ClearQueueOKSimpleMQ
	Set   bool
}

// IsSet returns true if OptClearQueueOKSimpleMQ was set.
func (o OptClearQueueOKSimpleMQ) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptClearQueueOKSimpleMQ) Reset() {
	var v ClearQueueOKSimpleMQ
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptClearQueueOKSimpleMQ) SetTo(v ClearQueueOKSimpleMQ) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptClearQueueOKSimpleMQ) Get() (v ClearQueueOKSimpleMQ, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptClearQueueOKSimpleMQ) Or(d ClearQueueOKSimpleMQ) ClearQueueOKSimpleMQ {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCommonServiceItemIconID returns new OptCommonServiceItemIconID with value set to v.
func NewOptCommonServiceItemIconID(v CommonServiceItemIconID) OptCommonServiceItemIconID {
	return OptCommonServiceItemIconID{
		Value: v,
		Set:   true,
	}
}

// OptCommonServiceItemIconID is optional CommonServiceItemIconID.
type OptCommonServiceItemIconID struct {
	Value CommonServiceItemIconID
	Set   bool
}

// IsSet returns true if OptCommonServiceItemIconID was set.
func (o OptCommonServiceItemIconID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCommonServiceItemIconID) Reset() {
	var v CommonServiceItemIconID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCommonServiceItemIconID) SetTo(v CommonServiceItemIconID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCommonServiceItemIconID) Get() (v CommonServiceItemIconID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCommonServiceItemIconID) Or(d CommonServiceItemIconID) CommonServiceItemIconID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptConfigQueueRequestCommonServiceItemIconID returns new OptConfigQueueRequestCommonServiceItemIconID with value set to v.
func NewOptConfigQueueRequestCommonServiceItemIconID(v ConfigQueueRequestCommonServiceItemIconID) OptConfigQueueRequestCommonServiceItemIconID {
	return OptConfigQueueRequestCommonServiceItemIconID{
		Value: v,
		Set:   true,
	}
}

// OptConfigQueueRequestCommonServiceItemIconID is optional ConfigQueueRequestCommonServiceItemIconID.
type OptConfigQueueRequestCommonServiceItemIconID struct {
	Value ConfigQueueRequestCommonServiceItemIconID
	Set   bool
}

// IsSet returns true if OptConfigQueueRequestCommonServiceItemIconID was set.
func (o OptConfigQueueRequestCommonServiceItemIconID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptConfigQueueRequestCommonServiceItemIconID) Reset() {
	var v ConfigQueueRequestCommonServiceItemIconID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptConfigQueueRequestCommonServiceItemIconID) SetTo(v ConfigQueueRequestCommonServiceItemIconID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptConfigQueueRequestCommonServiceItemIconID) Get() (v ConfigQueueRequestCommonServiceItemIconID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptConfigQueueRequestCommonServiceItemIconID) Or(d ConfigQueueRequestCommonServiceItemIconID) ConfigQueueRequestCommonServiceItemIconID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateQueueRequestCommonServiceItemIconID returns new OptCreateQueueRequestCommonServiceItemIconID with value set to v.
func NewOptCreateQueueRequestCommonServiceItemIconID(v CreateQueueRequestCommonServiceItemIconID) OptCreateQueueRequestCommonServiceItemIconID {
	return OptCreateQueueRequestCommonServiceItemIconID{
		Value: v,
		Set:   true,
	}
}

// OptCreateQueueRequestCommonServiceItemIconID is optional CreateQueueRequestCommonServiceItemIconID.
type OptCreateQueueRequestCommonServiceItemIconID struct {
	Value CreateQueueRequestCommonServiceItemIconID
	Set   bool
}

// IsSet returns true if OptCreateQueueRequestCommonServiceItemIconID was set.
func (o OptCreateQueueRequestCommonServiceItemIconID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateQueueRequestCommonServiceItemIconID) Reset() {
	var v CreateQueueRequestCommonServiceItemIconID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateQueueRequestCommonServiceItemIconID) SetTo(v CreateQueueRequestCommonServiceItemIconID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateQueueRequestCommonServiceItemIconID) Get() (v CreateQueueRequestCommonServiceItemIconID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateQueueRequestCommonServiceItemIconID) Or(d CreateQueueRequestCommonServiceItemIconID) CreateQueueRequestCommonServiceItemIconID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCommonServiceItemIcon returns new OptNilCommonServiceItemIcon with value set to v.
func NewOptNilCommonServiceItemIcon(v CommonServiceItemIcon) OptNilCommonServiceItemIcon {
	return OptNilCommonServiceItemIcon{
		Value: v,
		Set:   true,
	}
}

// OptNilCommonServiceItemIcon is optional nullable CommonServiceItemIcon.
type OptNilCommonServiceItemIcon struct {
	Value CommonServiceItemIcon
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCommonServiceItemIcon was set.
func (o OptNilCommonServiceItemIcon) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCommonServiceItemIcon) Reset() {
	var v CommonServiceItemIcon
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCommonServiceItemIcon) SetTo(v CommonServiceItemIcon) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCommonServiceItemIcon) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCommonServiceItemIcon) SetToNull() {
	o.Set = true
	o.Null = true
	var v CommonServiceItemIcon
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCommonServiceItemIcon) Get() (v CommonServiceItemIcon, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCommonServiceItemIcon) Or(d CommonServiceItemIcon) CommonServiceItemIcon {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilConfigQueueRequestCommonServiceItemIcon returns new OptNilConfigQueueRequestCommonServiceItemIcon with value set to v.
func NewOptNilConfigQueueRequestCommonServiceItemIcon(v ConfigQueueRequestCommonServiceItemIcon) OptNilConfigQueueRequestCommonServiceItemIcon {
	return OptNilConfigQueueRequestCommonServiceItemIcon{
		Value: v,
		Set:   true,
	}
}

// OptNilConfigQueueRequestCommonServiceItemIcon is optional nullable ConfigQueueRequestCommonServiceItemIcon.
type OptNilConfigQueueRequestCommonServiceItemIcon struct {
	Value ConfigQueueRequestCommonServiceItemIcon
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilConfigQueueRequestCommonServiceItemIcon was set.
func (o OptNilConfigQueueRequestCommonServiceItemIcon) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilConfigQueueRequestCommonServiceItemIcon) Reset() {
	var v ConfigQueueRequestCommonServiceItemIcon
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilConfigQueueRequestCommonServiceItemIcon) SetTo(v ConfigQueueRequestCommonServiceItemIcon) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilConfigQueueRequestCommonServiceItemIcon) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilConfigQueueRequestCommonServiceItemIcon) SetToNull() {
	o.Set = true
	o.Null = true
	var v ConfigQueueRequestCommonServiceItemIcon
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilConfigQueueRequestCommonServiceItemIcon) Get() (v ConfigQueueRequestCommonServiceItemIcon, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilConfigQueueRequestCommonServiceItemIcon) Or(d ConfigQueueRequestCommonServiceItemIcon) ConfigQueueRequestCommonServiceItemIcon {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateQueueRequestCommonServiceItemIcon returns new OptNilCreateQueueRequestCommonServiceItemIcon with value set to v.
func NewOptNilCreateQueueRequestCommonServiceItemIcon(v CreateQueueRequestCommonServiceItemIcon) OptNilCreateQueueRequestCommonServiceItemIcon {
	return OptNilCreateQueueRequestCommonServiceItemIcon{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateQueueRequestCommonServiceItemIcon is optional nullable CreateQueueRequestCommonServiceItemIcon.
type OptNilCreateQueueRequestCommonServiceItemIcon struct {
	Value CreateQueueRequestCommonServiceItemIcon
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateQueueRequestCommonServiceItemIcon was set.
func (o OptNilCreateQueueRequestCommonServiceItemIcon) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateQueueRequestCommonServiceItemIcon) Reset() {
	var v CreateQueueRequestCommonServiceItemIcon
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateQueueRequestCommonServiceItemIcon) SetTo(v CreateQueueRequestCommonServiceItemIcon) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateQueueRequestCommonServiceItemIcon) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateQueueRequestCommonServiceItemIcon) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateQueueRequestCommonServiceItemIcon
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateQueueRequestCommonServiceItemIcon) Get() (v CreateQueueRequestCommonServiceItemIcon, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateQueueRequestCommonServiceItemIcon) Or(d CreateQueueRequestCommonServiceItemIcon) CreateQueueRequestCommonServiceItemIcon {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Provider
type Provider struct {
	ID           int           `json:"ID"`
	Class        ProviderClass `json:"Class"`
	Name         string        `json:"Name"`
	ServiceClass string        `json:"ServiceClass"`
}

// GetID returns the value of ID.
func (s *Provider) GetID() int {
	return s.ID
}

// GetClass returns the value of Class.
func (s *Provider) GetClass() ProviderClass {
	return s.Class
}

// GetName returns the value of Name.
func (s *Provider) GetName() string {
	return s.Name
}

// GetServiceClass returns the value of ServiceClass.
func (s *Provider) GetServiceClass() string {
	return s.ServiceClass
}

// SetID sets the value of ID.
func (s *Provider) SetID(val int) {
	s.ID = val
}

// SetClass sets the value of Class.
func (s *Provider) SetClass(val ProviderClass) {
	s.Class = val
}

// SetName sets the value of Name.
func (s *Provider) SetName(val string) {
	s.Name = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *Provider) SetServiceClass(val string) {
	s.ServiceClass = val
}

type ProviderClass string

const (
	ProviderClassSimplemq ProviderClass = "simplemq"
)

// AllValues returns all ProviderClass values.
func (ProviderClass) AllValues() []ProviderClass {
	return []ProviderClass{
		ProviderClassSimplemq,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProviderClass) MarshalText() ([]byte, error) {
	switch s {
	case ProviderClassSimplemq:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProviderClass) UnmarshalText(data []byte) error {
	switch ProviderClass(data) {
	case ProviderClassSimplemq:
		*s = ProviderClassSimplemq
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type QueueName string

type RotateAPIKeyBadRequest Error

func (*RotateAPIKeyBadRequest) rotateAPIKeyRes() {}

type RotateAPIKeyInternalServerError Error

func (*RotateAPIKeyInternalServerError) rotateAPIKeyRes() {}

type RotateAPIKeyNotFound Error

func (*RotateAPIKeyNotFound) rotateAPIKeyRes() {}

type RotateAPIKeyOK struct {
	SimpleMQ RotateAPIKeyOKSimpleMQ `json:"SimpleMQ"`
	IsOk     OptBool                `json:"is_ok"`
}

// GetSimpleMQ returns the value of SimpleMQ.
func (s *RotateAPIKeyOK) GetSimpleMQ() RotateAPIKeyOKSimpleMQ {
	return s.SimpleMQ
}

// GetIsOk returns the value of IsOk.
func (s *RotateAPIKeyOK) GetIsOk() OptBool {
	return s.IsOk
}

// SetSimpleMQ sets the value of SimpleMQ.
func (s *RotateAPIKeyOK) SetSimpleMQ(val RotateAPIKeyOKSimpleMQ) {
	s.SimpleMQ = val
}

// SetIsOk sets the value of IsOk.
func (s *RotateAPIKeyOK) SetIsOk(val OptBool) {
	s.IsOk = val
}

func (*RotateAPIKeyOK) rotateAPIKeyRes() {}

type RotateAPIKeyOKSimpleMQ struct {
	Result OptString `json:"result"`
	Apikey string    `json:"apikey"`
}

// GetResult returns the value of Result.
func (s *RotateAPIKeyOKSimpleMQ) GetResult() OptString {
	return s.Result
}

// GetApikey returns the value of Apikey.
func (s *RotateAPIKeyOKSimpleMQ) GetApikey() string {
	return s.Apikey
}

// SetResult sets the value of Result.
func (s *RotateAPIKeyOKSimpleMQ) SetResult(val OptString) {
	s.Result = val
}

// SetApikey sets the value of Apikey.
func (s *RotateAPIKeyOKSimpleMQ) SetApikey(val string) {
	s.Apikey = val
}

type RotateAPIKeyUnauthorized Error

func (*RotateAPIKeyUnauthorized) rotateAPIKeyRes() {}

// Ref: #/components/schemas/Settings
type Settings struct {
	VisibilityTimeoutSeconds VisibilityTimeoutSeconds `json:"VisibilityTimeoutSeconds"`
	ExpireSeconds            ExpireSeconds            `json:"ExpireSeconds"`
}

// GetVisibilityTimeoutSeconds returns the value of VisibilityTimeoutSeconds.
func (s *Settings) GetVisibilityTimeoutSeconds() VisibilityTimeoutSeconds {
	return s.VisibilityTimeoutSeconds
}

// GetExpireSeconds returns the value of ExpireSeconds.
func (s *Settings) GetExpireSeconds() ExpireSeconds {
	return s.ExpireSeconds
}

// SetVisibilityTimeoutSeconds sets the value of VisibilityTimeoutSeconds.
func (s *Settings) SetVisibilityTimeoutSeconds(val VisibilityTimeoutSeconds) {
	s.VisibilityTimeoutSeconds = val
}

// SetExpireSeconds sets the value of ExpireSeconds.
func (s *Settings) SetExpireSeconds(val ExpireSeconds) {
	s.ExpireSeconds = val
}

// Ref: #/components/schemas/Status
type Status struct {
	// キュー名.
	QueueName string `json:"QueueName"`
}

// GetQueueName returns the value of QueueName.
func (s *Status) GetQueueName() string {
	return s.QueueName
}

// SetQueueName sets the value of QueueName.
func (s *Status) SetQueueName(val string) {
	s.QueueName = val
}

type VisibilityTimeoutSeconds int
