// Code generated by ogen, DO NOT EDIT.

package queue

// setDefaults set default value of fields.
func (s *ClearQueueOKSimpleMQ) setDefaults() {
	{
		val := string("success")
		s.Result.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConfigQueueRequestCommonServiceItemSettings) setDefaults() {
	{
		val := int(30)
		s.VisibilityTimeoutSeconds = val
	}
	{
		val := int(345600)
		s.ExpireSeconds = val
	}
}

// setDefaults set default value of fields.
func (s *GetMessageCountOKSimpleMQ) setDefaults() {
	{
		val := string("success")
		s.Result.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RotateAPIKeyOKSimpleMQ) setDefaults() {
	{
		val := string("success")
		s.Result.SetTo(val)
	}
}
