// Code generated by ogen, DO NOT EDIT.

package queue

// ClearQueueParams is parameters of clearQueue operation.
type ClearQueueParams struct {
	// キューのリソースID.
	ID string
}

// ConfigQueueParams is parameters of configQueue operation.
type ConfigQueueParams struct {
	// キューのリソースID.
	ID string
}

// DeleteQueueParams is parameters of deleteQueue operation.
type DeleteQueueParams struct {
	// キューのリソースID.
	ID string
}

// GetMessageCountParams is parameters of getMessageCount operation.
type GetMessageCountParams struct {
	// キューのリソースID.
	ID string
}

// GetQueueParams is parameters of getQueue operation.
type GetQueueParams struct {
	// キューのリソースID.
	ID string
}

// RotateAPIKeyParams is parameters of rotateAPIKey operation.
type RotateAPIKeyParams struct {
	// キューのリソースID.
	ID string
}
