// Code generated by ogen, DO NOT EDIT.

package sacloud

// OperationName is the ogen operation name
type OperationName = string

const (
	ClearQueueOperation      OperationName = "ClearQueue"
	ConfigQueueOperation     OperationName = "ConfigQueue"
	CreateQueueOperation     OperationName = "CreateQueue"
	DeleteQueueOperation     OperationName = "DeleteQueue"
	GetMessageCountOperation OperationName = "GetMessageCount"
	GetQueueOperation        OperationName = "GetQueue"
	GetQueuesOperation       OperationName = "GetQueues"
	RotateAPIKeyOperation    OperationName = "RotateAPIKey"
)
