// Code generated by ogen, DO NOT EDIT.
package sacloud

type ClearQueueRes interface {
	clearQueueRes()
}

type ConfigQueueRes interface {
	configQueueRes()
}

type CreateQueueRes interface {
	createQueueRes()
}

type DeleteQueueRes interface {
	deleteQueueRes()
}

type GetMessageCountRes interface {
	getMessageCountRes()
}

type GetQueueRes interface {
	getQueueRes()
}

type GetQueuesRes interface {
	getQueuesRes()
}

type RotateAPIKeyRes interface {
	rotateAPIKeyRes()
}
