// Code generated by ogen, DO NOT EDIT.

package message

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteMessageOperation        OperationName = "DeleteMessage"
	ExtendMessageTimeoutOperation OperationName = "ExtendMessageTimeout"
	ReceiveMessageOperation       OperationName = "ReceiveMessage"
	SendMessageOperation          OperationName = "SendMessage"
)
