// Code generated by ogen, DO NOT EDIT.

package message

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyAuth provides ApiKeyAuth security value.
	// キュー認証用のAPIキー.
	ApiKeyAuth(ctx context.Context, operationName OperationName) (ApiKeyAuth, error)
}

func (s *Client) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
