// Code generated by ogen, DO NOT EDIT.

package message

// DeleteMessageParams is parameters of deleteMessage operation.
type DeleteMessageParams struct {
	QueueName QueueName
	MessageId MessageId
}

// ExtendMessageTimeoutParams is parameters of extendMessageTimeout operation.
type ExtendMessageTimeoutParams struct {
	QueueName QueueName
	MessageId MessageId
}

// ReceiveMessageParams is parameters of receiveMessage operation.
type ReceiveMessageParams struct {
	QueueName QueueName
}

// SendMessageParams is parameters of sendMessage operation.
type SendMessageParams struct {
	QueueName QueueName
}
