// Code generated by ogen, DO NOT EDIT.
package message

type DeleteMessageRes interface {
	deleteMessageRes()
}

type ExtendMessageTimeoutRes interface {
	extendMessageTimeoutRes()
}

type ReceiveMessageRes interface {
	receiveMessageRes()
}

type SendMessageRes interface {
	sendMessageRes()
}
